export type State = {
  id: string;
  name: string;
  capital: string;
  region: "North" | "South" | "East" | "West" | "Central" | "Northeast";
  languages: string[];
  bestTime: string;
  attractions: string[];
  cuisine: string[];
  festivals: string[];
  unesco: string[];
  wildlife: string[];
  hillStations: string[];
  beaches: string[];
  culture: string;
  dress: string;
  adventure: string[];
  funFacts: string[];
  tips: string[];
  budget: string;
  duration: string;
  cities: string[];
  tags: ("beach" | "mountain" | "desert" | "forest" | "snow" | "luxury" | "culture" | "adventure" | "family" | "honeymoon" | "solo" | "pilgrimage" | "wildlife" | "food" | "history" | "photography")[];
  seasons: ("summer" | "winter" | "monsoon")[];
  budgetTier: 1 | 2 | 3 | 4; // 5k, 10k, 20k, 50k+
  hero: string;
  gallery: string[];
  emoji: string;
  tagline: string;
};

const img = (seed: string) => `https://picsum.photos/seed/${seed}/1200/800`;

export const HEROES: Record<string,string> = {
  "rajasthan": "https://s7ap1.scene7.com/is/image/incredibleindia/hawa-mahal-jaipur-rajasthan-city-1-hero?qlt=82&ts=1742200253577",
  "kerala": "https://cdn.kimkim.com/files/a/images/e1a35f4ab7e5e6784135780f34bdd78938b9b4e0/original-4f787f7ae22b5331fd58eba80f67693d.jpg",
  "goa": "https://www.travelcenter.uk/blog/wp-content/uploads/2018/02/Palolem-Beach-India.jpg",
  "himachal": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzijChpYXeejgVJwwmRa2ELYIUzafZ-cqXHLV7DKTCUktny2lpEeGPPOs&s=10",
  "uttarakhand": "https://www.indianpanorama.in/assets/images/tourpackages/banner/highlights-of-uttarakhand.webp",
  "tamilnadu": "https://www.indianpanorama.in/assets/images/tourpackages/banner/temples-of-tamilnadu.webp",
  "karnataka": "https://karnatakatourism.org/ci/q_80,w_500/cms/wp-content/uploads/2025/06/world-heritage-day.jpg",
  "maharashtra": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS2JqYcbYVSd-wWFgqPkCsrSuScutOgFWo22xJuop91Tw&s=10",
  "gujarat": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQk9Sh-FDcSKKw5Tw8EvoZyBaRmR9FTVp52gHoM46McOXjw6Di9dqoDFBA&s=10",
  "punjab": "https://hldak.mmtcdn.com/prod-s3-hld-hpcmsadmin/holidays/images/cities/1350/m_destination_Amritsar_l_367_623.webp",
  "uttarpradesh": "https://urbanacres.in/wp-content/uploads/2025/01/Uttar-Pradesh-Attracts-%E2%82%B91-Trillion-in-Hospitality-Investment-Boosting-Tourism.jpg",
  "westbengal": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRgEYiKK9D_MHabM8V0888zx4V7quPJTsr_HvPchpNzy5kZJl1p231JX9Ds&s=10",
  "odisha": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqtox6w88EUJVN8h8mkLEahtpyxQCghrN5O_UZklsx7AYswo7_nFVWkZA&s=10",
  "assam": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTj34Q0wD2qrT4TlrMTEGdQE-0fO0sYgAPdQIPD7HVw5hHtEmLKLUB-7cjX&s=10",
  "bihar": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT-mXomm7tB4L0ltirF7ghGz5vPHAqmAt-NGJKQTnDtA8hKxWd3SRzVlgG-&s=10",
  "madhyapradesh": "https://etimg.etb2bimg.com/photo/113726069.cms",
  "andhra": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7k40J-k6zdvOh_zaVs8_HouYOGgHWpAkNJBU40y_WcQ&s=10",
  "telangana": "https://images.openai.com/static-rsc-4/B4kY8FxHESkkCKCYb-qmMGNSk5eASWPEoGghfo8HAPyursKnj_heWaFNugPFC-yMKHOFjMfhk04zpKRXFdKY0_Aoi4hbCYTJK7eONWOsfoE5Ib83ltheAY00jd-t3RcpjDpx-c1sK8B5tHTufrqUiU7XtqA4luJWD4LYuxtKYg_38Z-OZ5FYaT7Fmu4YByUO?purpose=fullsize",
  "chhattisgarh": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRuvzfG3WWwk_Ovh909xgxIu8ao-ZplBgi5wF9Vu7nUQWzaJKbHVg95l3xM&s=10",
  "jharkhand": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQOvu5wUh3R564x6JsiUmWRhJztZm13kedCXMYY0K4mJlxLTLyN3-9cEeo&s=10",
  "haryana": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVlD88A9ynbuS62dPuxbC8EwTTuCy36GcPIaOjCiofpJz4dKv8tEfdQ3nB&s=10",
  "arunachal": "https://images.openai.com/static-rsc-4/-huQ3bNMutqBY_1xa9kGrsyaTn_bXLXrZwfgMxPaWUcZGgkDyufP-zGEds8Ui_-yMGrGIY_YFVWjgJWgeEW9vhELQj9_mtkNjWjfvur-E5CZDEVXCY22OCRl9M49Ej3fAm55Eny15bmTxIqHhrMoj54kECKJlRrhSe6UL9VVroGcJ4sWeJ739LB1vRf6XXdv?purpose=inline",
  "meghalaya": "https://images.openai.com/static-rsc-4/9M_EUWarei0aYR4KAA4wIisLtJ7Ih6dD98FdBqZby00B7pLi-ahVsDvJ-wxdz6rdPmRXPXyeXpXSRZi5zetONmUlr0LH1kiXM12Efw-sobbS68Difp5ihJqMgACwuxgGLqgraYk3pdYPtaefWSvpxa_Ezr4ThIZq6L1sFRHeqRM?purpose=inline",
  "manipur": "https://images.openai.com/static-rsc-4/pdurQbV4l8D2T3AXW4w8cc-Xqdud8oba9aB-46_OMQXVcZJMXHVLYgvVUirrkotvnSJidjamTqe06SLFwPsTzv-etgMQK_a--RAIm6FXBs3zUHfRpnkmYgHs8ny4csK3Z4XQbdaahX4lEIIqyEQ5Qu0Dx8l0cQrPRb2_m60p2-c?purpose=inline",
  "mizoram": "https://images.openai.com/static-rsc-4/gYWt6ZJkK0C7MYltUBG6UqgFVh0Y6SNZIjgcty6pL5ErgCfAphx7XBevVQmMEXusPMkxavokwQVouwdkm28waU86r8_FrHKa7pruFvvThQUJ31j4W-20656XZRGILoO-bq6kWQtO201YU8JUPQx3i5n_fTaSixVsCfAgGQoaGYc9HSEqLymvOS3CRpPjihwY?purpose=fullsize",
  "nagaland": "https://images.openai.com/static-rsc-4/iy06ZRTRu7J_Lx4S5xUf7icrfpHlq-4XJiuowUgiDtg9oUlYxUDWzVic1SDv5-_7QRBngRTlYjxLrGwtM0HgEr7ujWRfccbfNEqM-11Y8cUahZ4hm1KfXL9r0EVP8rpCf1TRdws8Yag2JPp3AwgegOzXj6M0UIxUlO4djML2wvc?purpose=inline",
  "tripura": "https://images.openai.com/static-rsc-4/HpTNRFIe3AcXEyxSBWOgdk0hJYKbiOL79fhpL9Oc3Yrinp9OQVTkARrKp-l7STl1LjXupYqFYKo64zgHH1_3SZ_0IRZNN5Q5bj0qd7VG-5BdxLKA1WWHO7bRidirM207opboIXgck_pqoblazZFOlRRvrB_pn0g0pYF6-yVdFN8?purpose=inline",
  "sikkim": "https://images.openai.com/static-rsc-4/Byi6-MBKwDkXWpakAE88ABFsuaLauuY5y2l_wDrfKMX52swwlxfUMmEqPzHRPjpi0eup_3zRBQLtYSzwlV7G4yHefvnDaXSpnDgTVmDOpgOzGtoEHR3t6PUnYy-miXbM_Ih-6nlNd2JZKUFTQ38ZFG5lEJi3uVoGo1uhJ5VnPRQ?purpose=inline"
};


export const STATES: State[] = [
  {
    id: "rajasthan", name: "Rajasthan", capital: "Jaipur", region: "North",
    languages: ["Hindi", "Rajasthani"], bestTime: "October – March",
    attractions: ["Amber Fort", "Hawa Mahal", "City Palace", "Jaisalmer Fort", "Lake Pichola", "Mehrangarh Fort"],
    cuisine: ["Dal Baati Churma", "Laal Maas", "Ghewar", "Ker Sangri", "Pyaaz Kachori"],
    festivals: ["Pushkar Camel Fair", "Desert Festival", "Teej", "Gangaur"],
    unesco: ["Hill Forts of Rajasthan", "Jantar Mantar"],
    wildlife: ["Ranthambore National Park", "Sariska Tiger Reserve", "Keoladeo National Park"],
    hillStations: ["Mount Abu"], beaches: [],
    culture: "Land of kings — royal palaces, Rajput valor, folk music and vibrant bazaars.",
    dress: "Ghagra Choli, Bandhani sarees, Safa turbans",
    adventure: ["Desert safari", "Hot air ballooning", "Zip-lining at Neemrana"],
    funFacts: ["Largest state by area", "Home to the Thar Desert", "Jaipur is India's first planned city"],
    tips: ["Carry sunscreen", "Bargain in bazaars", "Avoid peak summer"],
    budget: "₹8,000 – ₹25,000", duration: "5 – 7 days",
    cities: ["Jaipur", "Udaipur", "Jodhpur", "Jaisalmer", "Pushkar"],
    tags: ["desert", "culture", "history", "luxury", "honeymoon", "photography", "family"],
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["rajasthan"], gallery: [img("rajasthan-1"), img("rajasthan-2"), img("rajasthan-3"), img("rajasthan-4")],
    emoji: "🏜️", tagline: "The Royal Desert Kingdom",
  },
  {
    id: "kerala", name: "Kerala", capital: "Thiruvananthapuram", region: "South",
    languages: ["Malayalam"], bestTime: "September – March",
    attractions: ["Alleppey Backwaters", "Munnar Tea Gardens", "Fort Kochi", "Wayanad", "Varkala Cliffs"],
    cuisine: ["Sadya", "Appam with Stew", "Karimeen Fry", "Puttu Kadala", "Malabar Biryani"],
    festivals: ["Onam", "Thrissur Pooram", "Vishu"],
    unesco: ["Western Ghats"], wildlife: ["Periyar Tiger Reserve", "Silent Valley"],
    hillStations: ["Munnar", "Wayanad", "Vagamon"], beaches: ["Kovalam", "Varkala", "Marari"],
    culture: "God's own country — houseboats, Kathakali, spice trails and Ayurveda.",
    dress: "Mundu, Kasavu saree", adventure: ["Houseboat cruise", "Trekking Chembra Peak", "Bamboo rafting"],
    funFacts: ["100% literacy rate", "First state to declare digital literacy", "Ayurveda's heartland"],
    tips: ["Try houseboat overnight", "Monsoon is magical", "Book Ayurveda in advance"],
    budget: "₹10,000 – ₹30,000", duration: "6 – 8 days",
    cities: ["Kochi", "Alleppey", "Munnar", "Trivandrum", "Wayanad"],
    tags: ["beach", "mountain", "forest", "honeymoon", "family", "food", "photography", "wildlife"],
    seasons: ["winter", "monsoon"], budgetTier: 3,
    hero: HEROES["kerala"], gallery: [img("kerala-1"), img("kerala-2"), img("kerala-3"), img("kerala-4")],
    emoji: "🌴", tagline: "God's Own Country",
  },
  {
    id: "goa", name: "Goa", capital: "Panaji", region: "West",
    languages: ["Konkani", "Portuguese influence"], bestTime: "November – February",
    attractions: ["Baga Beach", "Basilica of Bom Jesus", "Fort Aguada", "Dudhsagar Falls", "Anjuna Flea Market"],
    cuisine: ["Fish Curry Rice", "Vindaloo", "Bebinca", "Xacuti", "Prawn Balchão"],
    festivals: ["Carnival", "Sunburn", "Shigmo"],
    unesco: ["Churches and Convents of Goa"], wildlife: ["Bhagwan Mahavir Sanctuary"],
    hillStations: [], beaches: ["Baga", "Palolem", "Anjuna", "Vagator", "Agonda"],
    culture: "Portuguese-Indian fusion — beaches, susegad vibes, cathedrals and cashew feni.",
    dress: "Casual western + traditional Pano Bhaju",
    adventure: ["Parasailing", "Scuba diving at Grande Island", "Dudhsagar trek"],
    funFacts: ["Smallest state by area", "Was a Portuguese colony until 1961"],
    tips: ["Rent a scooter", "South Goa is calmer", "Try feni"],
    budget: "₹8,000 – ₹25,000", duration: "4 – 6 days",
    cities: ["Panaji", "Margao", "Vasco", "Calangute"],
    tags: ["beach", "honeymoon", "friends", "food", "adventure", "photography"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["goa"], gallery: [img("goa-1"), img("goa-2"), img("goa-3"), img("goa-4")],
    emoji: "🏖️", tagline: "Sun, Sand & Susegad",
  },
  {
    id: "himachal", name: "Himachal Pradesh", capital: "Shimla", region: "North",
    languages: ["Hindi", "Pahari"], bestTime: "March – June, October – February",
    attractions: ["Rohtang Pass", "Solang Valley", "The Ridge Shimla", "Spiti Valley", "Bir Billing"],
    cuisine: ["Dham", "Siddu", "Chha Gosht", "Babru", "Tudkiya Bhath"],
    festivals: ["Kullu Dussehra", "Losar", "Shivratri Mandi"],
    unesco: ["Great Himalayan National Park", "Kalka–Shimla Railway"],
    wildlife: ["Great Himalayan NP", "Pin Valley"], hillStations: ["Shimla", "Manali", "Dharamshala", "Kasol", "Dalhousie"],
    beaches: [],
    culture: "Himalayan serenity — monasteries, apple orchards, snow trails.",
    dress: "Kullu shawl, Pahari cap",
    adventure: ["Paragliding at Bir", "Skiing at Solang", "Trekking Hampta Pass", "River rafting Kullu"],
    funFacts: ["Home to Dalai Lama in McLeodganj", "Toy train UNESCO site"],
    tips: ["Layer up", "Check road status in winter", "Altitude — hydrate"],
    budget: "₹10,000 – ₹30,000", duration: "6 – 9 days",
    cities: ["Shimla", "Manali", "Dharamshala", "Kasol", "Spiti"],
    tags: ["mountain", "snow", "adventure", "honeymoon", "solo", "photography"] as any,
    seasons: ["summer", "winter"], budgetTier: 3,
    hero: HEROES["himachal"], gallery: [img("himachal-1"), img("himachal-2"), img("himachal-3"), img("himachal-4")],
    emoji: "🏔️", tagline: "Abode of Snow",
  },
  {
    id: "uttarakhand", name: "Uttarakhand", capital: "Dehradun", region: "North",
    languages: ["Hindi", "Garhwali", "Kumaoni"], bestTime: "March – June, September – November",
    attractions: ["Rishikesh", "Kedarnath", "Nainital", "Valley of Flowers", "Auli"],
    cuisine: ["Kafuli", "Bal Mithai", "Aloo Ke Gutke", "Bhang ki Chutney"],
    festivals: ["Kumbh Mela", "Ganga Dussehra", "Nanda Devi Raj Jat"],
    unesco: ["Nanda Devi & Valley of Flowers NP"],
    wildlife: ["Jim Corbett", "Rajaji NP"], hillStations: ["Nainital", "Mussoorie", "Auli", "Chopta"],
    beaches: [],
    culture: "Devbhoomi — sacred rivers, Char Dham pilgrimages, yoga capital of the world.",
    dress: "Ghagri, Pichhora",
    adventure: ["White water rafting", "Bungee at Rishikesh", "Skiing at Auli", "Char Dham trek"],
    funFacts: ["Corbett is India's oldest national park", "Rishikesh = yoga capital"],
    tips: ["Book Char Dham early", "Respect temple etiquette", "Layer in higher altitudes"],
    budget: "₹8,000 – ₹25,000", duration: "5 – 8 days",
    cities: ["Dehradun", "Rishikesh", "Haridwar", "Nainital", "Mussoorie"],
    tags: ["mountain", "adventure", "pilgrimage", "wildlife", "snow", "solo"] as any,
    seasons: ["summer", "winter"], budgetTier: 2,
    hero: HEROES["uttarakhand"], gallery: [img("uk-1"), img("uk-2"), img("uk-3"), img("uk-4")],
    emoji: "🕉️", tagline: "Land of the Gods",
  },
  {
    id: "tamilnadu", name: "Tamil Nadu", capital: "Chennai", region: "South",
    languages: ["Tamil"], bestTime: "November – March",
    attractions: ["Meenakshi Temple", "Marina Beach", "Mahabalipuram", "Ooty", "Rameshwaram"],
    cuisine: ["Dosa", "Idli Sambar", "Chettinad Chicken", "Filter Coffee", "Pongal"],
    festivals: ["Pongal", "Natyanjali", "Karthigai Deepam"],
    unesco: ["Great Living Chola Temples", "Mahabalipuram Monuments", "Nilgiri Mountain Railway"],
    wildlife: ["Mudumalai NP", "Anamalai Tiger Reserve"],
    hillStations: ["Ooty", "Kodaikanal", "Yercaud"], beaches: ["Marina", "Kovalam TN", "Rameshwaram"],
    culture: "Dravidian temples, classical dance, ancient Tamil literature.",
    dress: "Kanjeevaram saree, Veshti",
    adventure: ["Trekking Kolli Hills", "Surfing Kovalam"],
    funFacts: ["Meenakshi Temple has 33,000 sculptures", "Marina is India's longest urban beach"],
    tips: ["Dress modestly at temples", "Try filter coffee everywhere"],
    budget: "₹8,000 – ₹22,000", duration: "6 – 8 days",
    cities: ["Chennai", "Madurai", "Coimbatore", "Ooty", "Thanjavur"],
    tags: ["culture", "history", "beach", "mountain", "food", "pilgrimage"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["tamilnadu"], gallery: [img("tn-1"), img("tn-2"), img("tn-3"), img("tn-4")],
    emoji: "🛕", tagline: "Temples & Traditions",
  },
  {
    id: "karnataka", name: "Karnataka", capital: "Bengaluru", region: "South",
    languages: ["Kannada"], bestTime: "October – March",
    attractions: ["Hampi", "Mysore Palace", "Coorg", "Gokarna", "Jog Falls"],
    cuisine: ["Bisi Bele Bath", "Mysore Masala Dosa", "Ragi Mudde", "Mangalorean Fish Curry"],
    festivals: ["Mysore Dasara", "Ugadi", "Karaga"],
    unesco: ["Hampi", "Pattadakal", "Western Ghats"],
    wildlife: ["Bandipur", "Nagarhole", "Dandeli"],
    hillStations: ["Coorg", "Chikmagalur", "Sakleshpur"], beaches: ["Gokarna", "Karwar", "Murudeshwar"],
    culture: "Ancient empires, coffee plantations, tech capital of India.",
    dress: "Ilkal saree, Mysore silk",
    adventure: ["Trekking Kudremukh", "Coracle at Hogenakkal", "River rafting Dandeli"],
    funFacts: ["Hampi was once the world's second-largest city", "Bengaluru is called Silicon Valley of India"],
    tips: ["Coffee estates need advance booking", "Hampi is best at sunrise"],
    budget: "₹10,000 – ₹28,000", duration: "6 – 8 days",
    cities: ["Bengaluru", "Mysuru", "Hampi", "Coorg", "Mangaluru"],
    tags: ["history", "beach", "mountain", "wildlife", "food", "photography"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["karnataka"], gallery: [img("ka-1"), img("ka-2"), img("ka-3"), img("ka-4")],
    emoji: "☕", tagline: "One State, Many Worlds",
  },
  {
    id: "maharashtra", name: "Maharashtra", capital: "Mumbai", region: "West",
    languages: ["Marathi"], bestTime: "October – March",
    attractions: ["Gateway of India", "Ajanta & Ellora", "Lonavala", "Marine Drive", "Shirdi"],
    cuisine: ["Vada Pav", "Puran Poli", "Misal Pav", "Pav Bhaji", "Modak"],
    festivals: ["Ganesh Chaturthi", "Gudi Padwa", "Nashik Kumbh"],
    unesco: ["Ajanta Caves", "Ellora Caves", "Elephanta Caves", "Chhatrapati Shivaji Terminus"],
    wildlife: ["Tadoba", "Sanjay Gandhi NP"],
    hillStations: ["Lonavala", "Mahabaleshwar", "Matheran"], beaches: ["Alibaug", "Ganpatipule", "Tarkarli"],
    culture: "Bollywood, Maratha history, cave paintings, monsoon romance.",
    dress: "Nauvari saree, Dhoti-Pheta",
    adventure: ["Trekking Sahyadri", "Scuba at Tarkarli", "Rappelling Kalsubai"],
    funFacts: ["Bollywood is based here", "Ellora has caves of 3 religions"],
    tips: ["Beat Mumbai traffic — use locals", "Monsoon transforms Sahyadris"],
    budget: "₹8,000 – ₹28,000", duration: "5 – 7 days",
    cities: ["Mumbai", "Pune", "Aurangabad", "Nashik", "Lonavala"],
    tags: ["history", "beach", "food", "adventure", "photography", "family"] as any,
    seasons: ["winter", "monsoon"], budgetTier: 3,
    hero: HEROES["maharashtra"], gallery: [img("mh-1"), img("mh-2"), img("mh-3"), img("mh-4")],
    emoji: "🎭", tagline: "The Land of Warriors",
  },
  {
    id: "gujarat", name: "Gujarat", capital: "Gandhinagar", region: "West",
    languages: ["Gujarati"], bestTime: "November – February",
    attractions: ["Rann of Kutch", "Statue of Unity", "Somnath Temple", "Gir NP", "Dwarka"],
    cuisine: ["Dhokla", "Thepla", "Undhiyu", "Fafda", "Khandvi"],
    festivals: ["Navratri", "Rann Utsav", "Uttarayan (Kite Festival)"],
    unesco: ["Rani ki Vav", "Champaner-Pavagadh", "Ahmedabad Historic City", "Dholavira"],
    wildlife: ["Gir NP (only Asiatic lions)", "Little Rann"],
    hillStations: ["Saputara"], beaches: ["Diu", "Mandvi"],
    culture: "Business hub, garba nights, white desert, Gandhi's homeland.",
    dress: "Chaniya Choli, Kediyu",
    adventure: ["White desert camping", "Wildlife safari Gir", "Kite flying Ahmedabad"],
    funFacts: ["World's tallest statue (Statue of Unity)", "Only place with Asiatic lions"],
    tips: ["Rann Utsav Nov–Feb", "Dry state — no alcohol"],
    budget: "₹8,000 – ₹22,000", duration: "5 – 7 days",
    cities: ["Ahmedabad", "Surat", "Vadodara", "Rajkot", "Bhuj"],
    tags: ["desert", "culture", "history", "wildlife", "family", "photography"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["gujarat"], gallery: [img("gj-1"), img("gj-2"), img("gj-3"), img("gj-4")],
    emoji: "🦁", tagline: "The Vibrant West",
  },
  {
    id: "punjab", name: "Punjab", capital: "Chandigarh", region: "North",
    languages: ["Punjabi"], bestTime: "October – March",
    attractions: ["Golden Temple", "Wagah Border", "Jallianwala Bagh", "Rock Garden"],
    cuisine: ["Butter Chicken", "Sarson da Saag", "Makki di Roti", "Amritsari Kulcha", "Lassi"],
    festivals: ["Baisakhi", "Lohri", "Hola Mohalla"],
    unesco: [], wildlife: ["Harike Wetland"], hillStations: [], beaches: [],
    culture: "Bhangra beats, Sikh heritage, hearty food, warm hospitality.",
    dress: "Patiala Salwar, Kurta Pyjama with turban",
    adventure: ["Farm tourism", "Cycling border trails"],
    funFacts: ["Golden Temple serves 100,000 free meals daily", "Chandigarh is India's first planned modern city"],
    tips: ["Try langar at Golden Temple", "Attend Wagah ceremony evening"],
    budget: "₹6,000 – ₹18,000", duration: "3 – 5 days",
    cities: ["Amritsar", "Chandigarh", "Ludhiana", "Patiala"],
    tags: ["culture", "pilgrimage", "food", "history", "family"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["punjab"], gallery: [img("pb-1"), img("pb-2"), img("pb-3"), img("pb-4")],
    emoji: "☬", tagline: "Land of Five Rivers",
  },
  {
    id: "uttarpradesh", name: "Uttar Pradesh", capital: "Lucknow", region: "North",
    languages: ["Hindi", "Urdu"], bestTime: "October – March",
    attractions: ["Taj Mahal", "Varanasi Ghats", "Fatehpur Sikri", "Ayodhya", "Bara Imambara"],
    cuisine: ["Awadhi Biryani", "Kebabs", "Chaat", "Petha", "Malaiyo"],
    festivals: ["Kumbh Mela", "Dev Deepawali", "Ram Navami"],
    unesco: ["Taj Mahal", "Agra Fort", "Fatehpur Sikri"],
    wildlife: ["Dudhwa NP"], hillStations: [], beaches: [],
    culture: "Cradle of civilization — Mughal grandeur, spiritual Varanasi, Nawabi refinement.",
    dress: "Chikankari kurtas, Sherwani",
    adventure: ["Boat rides Ganges", "Heritage walks"],
    funFacts: ["Home to 3 UNESCO sites", "Varanasi is one of world's oldest living cities"],
    tips: ["Sunrise on Ganga Ghats is unmissable", "Taj closes on Fridays"],
    budget: "₹7,000 – ₹20,000", duration: "5 – 7 days",
    cities: ["Agra", "Varanasi", "Lucknow", "Ayodhya", "Mathura"],
    tags: ["history", "pilgrimage", "culture", "photography", "food"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["uttarpradesh"], gallery: [img("up-1"), img("up-2"), img("up-3"), img("up-4")],
    emoji: "🕌", tagline: "Heartland of Heritage",
  },
  {
    id: "westbengal", name: "West Bengal", capital: "Kolkata", region: "East",
    languages: ["Bengali"], bestTime: "October – March",
    attractions: ["Victoria Memorial", "Sundarbans", "Darjeeling", "Howrah Bridge", "Kalighat"],
    cuisine: ["Rosogolla", "Mishti Doi", "Fish Curry", "Kathi Roll", "Sondesh"],
    festivals: ["Durga Puja", "Poila Boishakh", "Rath Yatra"],
    unesco: ["Sundarbans NP", "Darjeeling Himalayan Railway"],
    wildlife: ["Sundarbans (Royal Bengal Tiger)", "Buxa Tiger Reserve"],
    hillStations: ["Darjeeling", "Kalimpong"], beaches: ["Digha", "Mandarmani"],
    culture: "Literature, art, football, tea gardens and the biggest Durga Puja on earth.",
    dress: "Tant saree, Dhuti-Punjabi",
    adventure: ["Toy train ride", "Sundarbans mangrove tour", "Trekking Sandakphu"],
    funFacts: ["Kolkata's Durga Puja is a UNESCO Intangible Heritage", "Sundarbans is world's largest mangrove"],
    tips: ["Try street kathi rolls", "Book Sundarbans permits early"],
    budget: "₹8,000 – ₹22,000", duration: "5 – 8 days",
    cities: ["Kolkata", "Darjeeling", "Siliguri", "Sundarban"],
    tags: ["culture", "wildlife", "mountain", "food", "history", "photography"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["westbengal"], gallery: [img("wb-1"), img("wb-2"), img("wb-3"), img("wb-4")],
    emoji: "🐅", tagline: "The Cultural Capital",
  },
  {
    id: "odisha", name: "Odisha", capital: "Bhubaneswar", region: "East",
    languages: ["Odia"], bestTime: "October – February",
    attractions: ["Konark Sun Temple", "Puri Beach", "Jagannath Temple", "Chilika Lake", "Udayagiri Caves"],
    cuisine: ["Dalma", "Chhena Poda", "Machha Besara", "Pakhala"],
    festivals: ["Rath Yatra", "Konark Dance Festival", "Durga Puja"],
    unesco: ["Konark Sun Temple"], wildlife: ["Similipal", "Bhitarkanika"],
    hillStations: ["Daringbadi"], beaches: ["Puri", "Gopalpur", "Chandipur"],
    culture: "Odissi dance, ancient temples, tribal art, Bay of Bengal coast.",
    dress: "Sambalpuri saree", adventure: ["Chilika dolphin tour", "Trekking Similipal"],
    funFacts: ["Chilika is Asia's largest brackish water lagoon", "Chandipur beach 'disappears' at low tide"],
    tips: ["Rath Yatra is world-famous", "Non-Hindus can view Jagannath temple from outside only"],
    budget: "₹7,000 – ₹18,000", duration: "5 – 7 days",
    cities: ["Bhubaneswar", "Puri", "Konark", "Cuttack"],
    tags: ["beach", "pilgrimage", "history", "culture", "wildlife"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["odisha"], gallery: [img("od-1"), img("od-2"), img("od-3"), img("od-4")],
    emoji: "🌅", tagline: "Soul of India",
  },
  {
    id: "assam", name: "Assam", capital: "Dispur", region: "Northeast",
    languages: ["Assamese"], bestTime: "November – April",
    attractions: ["Kaziranga NP", "Kamakhya Temple", "Majuli Island", "Sivasagar", "Tea gardens"],
    cuisine: ["Masor Tenga", "Pitha", "Khar", "Assam Tea"],
    festivals: ["Bihu", "Ambubachi Mela"],
    unesco: ["Kaziranga NP", "Manas NP"],
    wildlife: ["Kaziranga (One-horned Rhino)", "Manas", "Nameri"],
    hillStations: ["Haflong"], beaches: [],
    culture: "One-horned rhinos, silk weaving, tea heritage, Brahmaputra life.",
    dress: "Mekhela Chador", adventure: ["Jeep safari Kaziranga", "River cruise Brahmaputra"],
    funFacts: ["Home to 2/3 of world's one-horned rhinos", "Majuli is world's largest river island"],
    tips: ["Safari opens Nov", "Try Assam tea at source"],
    budget: "₹9,000 – ₹22,000", duration: "5 – 7 days",
    cities: ["Guwahati", "Jorhat", "Dibrugarh", "Tezpur"],
    tags: ["wildlife", "culture", "forest", "photography"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["assam"], gallery: [img("as-1"), img("as-2"), img("as-3"), img("as-4")],
    emoji: "🦏", tagline: "Land of Red River",
  },
  {
    id: "bihar", name: "Bihar", capital: "Patna", region: "East",
    languages: ["Hindi", "Bhojpuri", "Maithili"], bestTime: "October – March",
    attractions: ["Bodh Gaya", "Nalanda Ruins", "Rajgir", "Vaishali"],
    cuisine: ["Litti Chokha", "Sattu Paratha", "Thekua"],
    festivals: ["Chhath Puja", "Sonepur Mela"],
    unesco: ["Mahabodhi Temple, Bodh Gaya", "Nalanda Mahavihara"],
    wildlife: ["Valmiki Tiger Reserve"], hillStations: [], beaches: [],
    culture: "Birthplace of Buddhism and Jainism, ancient universities.",
    dress: "Tussar silk saree", adventure: ["Trekking Rajgir hills"],
    funFacts: ["Nalanda was world's first residential university", "Buddha attained enlightenment in Bodh Gaya"],
    tips: ["Winter is ideal", "Bodh Gaya has Buddhist temples of many countries"],
    budget: "₹5,000 – ₹15,000", duration: "3 – 5 days",
    cities: ["Patna", "Gaya", "Nalanda", "Rajgir"],
    tags: ["pilgrimage", "history", "culture"] as any,
    seasons: ["winter"], budgetTier: 1,
    hero: HEROES["bihar"], gallery: [img("br-1"), img("br-2"), img("br-3"), img("br-4")],
    emoji: "☸️", tagline: "Where Buddha Awakened",
  },
  {
    id: "madhyapradesh", name: "Madhya Pradesh", capital: "Bhopal", region: "Central",
    languages: ["Hindi"], bestTime: "October – March",
    attractions: ["Khajuraho", "Sanchi Stupa", "Bandhavgarh", "Kanha", "Gwalior Fort", "Bhimbetka"],
    cuisine: ["Poha Jalebi", "Bhutte ki Kees", "Dal Bafla", "Sabudana Khichdi"],
    festivals: ["Khajuraho Dance Festival", "Lokrang"],
    unesco: ["Khajuraho", "Sanchi", "Bhimbetka Rock Shelters"],
    wildlife: ["Bandhavgarh", "Kanha", "Pench", "Panna"],
    hillStations: ["Pachmarhi"], beaches: [],
    culture: "Heart of India — tigers, temples and tribal traditions.",
    dress: "Chanderi & Maheshwari sarees",
    adventure: ["Tiger safari", "Trekking Pachmarhi", "Boating Bhedaghat"],
    funFacts: ["India's tiger capital", "3 UNESCO sites"],
    tips: ["Book tiger safaris in advance", "Winter for best sightings"],
    budget: "₹9,000 – ₹28,000", duration: "6 – 9 days",
    cities: ["Bhopal", "Indore", "Khajuraho", "Gwalior", "Ujjain"],
    tags: ["wildlife", "history", "forest", "pilgrimage", "photography"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["madhyapradesh"], gallery: [img("mp-1"), img("mp-2"), img("mp-3"), img("mp-4")],
    emoji: "🐯", tagline: "The Heart of India",
  },
  {
    id: "andhra", name: "Andhra Pradesh", capital: "Amaravati", region: "South",
    languages: ["Telugu"], bestTime: "October – March",
    attractions: ["Tirupati", "Araku Valley", "Borra Caves", "Lepakshi", "Vizag Beaches"],
    cuisine: ["Hyderabadi Biryani", "Gongura Pachadi", "Pesarattu", "Pulihora"],
    festivals: ["Ugadi", "Sankranti", "Brahmotsavam"],
    unesco: [], wildlife: ["Nagarjunasagar Srisailam Tiger Reserve"],
    hillStations: ["Araku"], beaches: ["Rushikonda", "Visakhapatnam", "Bheemunipatnam"],
    culture: "Kuchipudi dance, Telugu cinema, temple architecture, spicy cuisine.",
    dress: "Pochampally saree",
    adventure: ["Trekking Araku", "Scuba Visakhapatnam"],
    funFacts: ["Tirupati is world's richest temple", "Second longest coastline"],
    tips: ["Book Tirupati darshan online", "Try Andhra meals — very spicy"],
    budget: "₹7,000 – ₹20,000", duration: "5 – 7 days",
    cities: ["Visakhapatnam", "Vijayawada", "Tirupati", "Amaravati"],
    tags: ["pilgrimage", "beach", "food", "culture", "mountain"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["andhra"], gallery: [img("ap-1"), img("ap-2"), img("ap-3"), img("ap-4")],
    emoji: "🌊", tagline: "The Sunrise State",
  },
  {
    id: "telangana", name: "Telangana", capital: "Hyderabad", region: "South",
    languages: ["Telugu", "Urdu"], bestTime: "October – February",
    attractions: ["Charminar", "Golconda Fort", "Ramoji Film City", "Warangal Fort", "Hussain Sagar"],
    cuisine: ["Hyderabadi Biryani", "Haleem", "Mirchi ka Salan", "Double ka Meetha"],
    festivals: ["Bathukamma", "Bonalu", "Ramzan"],
    unesco: ["Ramappa Temple"], wildlife: ["Kawal Tiger Reserve"],
    hillStations: [], beaches: [],
    culture: "Nizami elegance meets Telugu roots — pearls, biryani and IT boom.",
    dress: "Pochampally Ikat", adventure: ["Rock climbing Bhongir", "Zoo safari"],
    funFacts: ["Hyderabad is called City of Pearls", "Ramoji is world's largest film studio"],
    tips: ["Try old-city Hyderabadi biryani", "Charminar area gets crowded"],
    budget: "₹8,000 – ₹22,000", duration: "4 – 6 days",
    cities: ["Hyderabad", "Warangal", "Karimnagar"],
    tags: ["food", "history", "culture", "family"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["telangana"], gallery: [img("tg-1"), img("tg-2"), img("tg-3"), img("tg-4")],
    emoji: "🌙", tagline: "The Pearl City",
  },
  {
    id: "chhattisgarh", name: "Chhattisgarh", capital: "Raipur", region: "Central",
    languages: ["Hindi", "Chhattisgarhi"], bestTime: "October – March",
    attractions: ["Chitrakote Falls", "Bastar", "Kanger Valley NP", "Sirpur"],
    cuisine: ["Chila", "Faraa", "Muthia", "Aamat"],
    festivals: ["Bastar Dussehra", "Hareli", "Madai"],
    unesco: [], wildlife: ["Indravati NP", "Kanger Valley"],
    hillStations: ["Mainpat"], beaches: [],
    culture: "Tribal heartland — dense forests, waterfalls, ancient bell metal art.",
    dress: "Kosa silk saree", adventure: ["Waterfall trekking", "Cave exploration Kutumsar"],
    funFacts: ["Chitrakote is India's widest waterfall — the 'Niagara of India'", "Bastar Dussehra runs 75 days"],
    tips: ["Best combined with tribal tours", "Post-monsoon for waterfalls"],
    budget: "₹6,000 – ₹15,000", duration: "4 – 6 days",
    cities: ["Raipur", "Jagdalpur", "Bilaspur"],
    tags: ["forest", "adventure", "culture", "wildlife"] as any,
    seasons: ["winter", "monsoon"], budgetTier: 1,
    hero: HEROES["chhattisgarh"], gallery: [img("cg-1"), img("cg-2"), img("cg-3"), img("cg-4")],
    emoji: "🌊", tagline: "Land of Waterfalls & Tribes",
  },
  {
    id: "jharkhand", name: "Jharkhand", capital: "Ranchi", region: "East",
    languages: ["Hindi", "Santali"], bestTime: "October – March",
    attractions: ["Hundru Falls", "Betla NP", "Deoghar", "Netarhat"],
    cuisine: ["Litti Chokha", "Dhuska", "Rugra", "Handia"],
    festivals: ["Sarhul", "Karma", "Tusu Parab"],
    unesco: [], wildlife: ["Betla NP", "Palamau Tiger Reserve"],
    hillStations: ["Netarhat"], beaches: [],
    culture: "Tribal wisdom, mineral-rich forests, folk music.",
    dress: "Panchi Parhan", adventure: ["Trekking Parasnath", "Waterfall hikes"],
    funFacts: ["Netarhat is 'Queen of Chotanagpur'", "Parasnath is highest peak — sacred to Jains"],
    tips: ["Combine with Bihar for pilgrimage trips"],
    budget: "₹5,000 – ₹14,000", duration: "3 – 5 days",
    cities: ["Ranchi", "Jamshedpur", "Deoghar"],
    tags: ["forest", "adventure", "pilgrimage", "wildlife"] as any,
    seasons: ["winter"], budgetTier: 1,
    hero: HEROES["jharkhand"], gallery: [img("jh-1"), img("jh-2"), img("jh-3"), img("jh-4")],
    emoji: "🌳", tagline: "The Land of Forests",
  },
  {
    id: "haryana", name: "Haryana", capital: "Chandigarh", region: "North",
    languages: ["Hindi", "Haryanvi"], bestTime: "October – March",
    attractions: ["Kurukshetra", "Sultanpur Bird Sanctuary", "Pinjore Gardens", "Morni Hills"],
    cuisine: ["Bajra Khichdi", "Kachri ki Sabzi", "Bathua Raita", "Lassi"],
    festivals: ["Surajkund Mela", "Teej", "Gita Jayanti"],
    unesco: [], wildlife: ["Sultanpur NP"], hillStations: ["Morni"], beaches: [],
    culture: "Rural roots, wrestling akhadas, Mahabharata land.",
    dress: "Ghagra & Kurti", adventure: ["Bird watching Sultanpur"],
    funFacts: ["Kurukshetra was Mahabharata battlefield", "Surajkund crafts fair is India's biggest"],
    tips: ["Great weekend trip from Delhi", "Attend Surajkund in Feb"],
    budget: "₹5,000 – ₹14,000", duration: "2 – 4 days",
    cities: ["Chandigarh", "Gurgaon", "Kurukshetra", "Panchkula"],
    tags: ["history", "culture", "family"] as any,
    seasons: ["winter"], budgetTier: 1,
    hero: HEROES["haryana"], gallery: [img("hr-1"), img("hr-2"), img("hr-3"), img("hr-4")],
    emoji: "🏇", tagline: "Karam Bhoomi",
  },
  {
    id: "arunachal", name: "Arunachal Pradesh", capital: "Itanagar", region: "Northeast",
    languages: ["English", "many tribal languages"], bestTime: "October – April",
    attractions: ["Tawang Monastery", "Sela Pass", "Ziro Valley", "Namdapha NP"],
    cuisine: ["Thukpa", "Momos", "Apong", "Zan"],
    festivals: ["Losar", "Ziro Music Festival", "Nyokum"],
    unesco: [], wildlife: ["Namdapha NP", "Pakke Tiger Reserve"],
    hillStations: ["Tawang", "Bomdila", "Ziro"], beaches: [],
    culture: "Land of dawn-lit mountains — Buddhist monasteries, tribal diversity.",
    dress: "Gale (women), Bakh (men)", adventure: ["Trekking Tawang", "Rafting Siang"],
    funFacts: ["First state to see the sunrise in India", "Home to 26 major tribes"],
    tips: ["Need Inner Line Permit", "Roads are rough — plan buffer days"],
    budget: "₹15,000 – ₹35,000", duration: "7 – 10 days",
    cities: ["Itanagar", "Tawang", "Ziro", "Bomdila"],
    tags: ["mountain", "adventure", "culture", "snow", "photography"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["arunachal"], gallery: [img("ar-1"), img("ar-2"), img("ar-3"), img("ar-4")],
    emoji: "🏯", tagline: "Land of Dawn-Lit Mountains",
  },
  {
    id: "meghalaya", name: "Meghalaya", capital: "Shillong", region: "Northeast",
    languages: ["Khasi", "Garo", "English"], bestTime: "October – May",
    attractions: ["Cherrapunji", "Living Root Bridges", "Dawki River", "Mawsynram", "Mawlynnong"],
    cuisine: ["Jadoh", "Dohkhlieh", "Nakham Bitchi"],
    festivals: ["Wangala", "Shad Suk Mynsiem", "Nongkrem"],
    unesco: [], wildlife: ["Nokrek", "Balpakram"],
    hillStations: ["Shillong", "Cherrapunji"], beaches: [],
    culture: "Abode of clouds — matrilineal societies, waterfalls, cleanest village.",
    dress: "Jainsem, Dhara",
    adventure: ["Root bridge trek", "Kayaking Dawki", "Caving Krem Liat Prah"],
    funFacts: ["Mawsynram is wettest place on Earth", "Mawlynnong = cleanest village in Asia", "Dawki has crystal-clear water"],
    tips: ["Carry rain jacket year-round", "October–April driest"],
    budget: "₹12,000 – ₹28,000", duration: "5 – 7 days",
    cities: ["Shillong", "Cherrapunji", "Dawki", "Tura"],
    tags: ["mountain", "forest", "adventure", "honeymoon", "photography"] as any,
    seasons: ["winter", "monsoon"], budgetTier: 3,
    hero: HEROES["meghalaya"], gallery: [img("ml-1"), img("ml-2"), img("ml-3"), img("ml-4")],
    emoji: "☁️", tagline: "Abode of Clouds",
  },
  {
    id: "manipur", name: "Manipur", capital: "Imphal", region: "Northeast",
    languages: ["Meitei"], bestTime: "October – March",
    attractions: ["Loktak Lake", "Kangla Fort", "Keibul Lamjao NP", "Ima Market"],
    cuisine: ["Eromba", "Chak-hao Kheer", "Singju"],
    festivals: ["Yaoshang", "Ningol Chakouba", "Sangai Festival"],
    unesco: [], wildlife: ["Keibul Lamjao (only floating NP)"],
    hillStations: ["Ukhrul"], beaches: [],
    culture: "Jewel of India — floating islands, classical dance, martial arts.",
    dress: "Innaphi, Phanek", adventure: ["Boating Loktak", "Trekking Dzukou"],
    funFacts: ["Only floating national park in the world", "Manipuri dance is one of 8 Indian classical forms"],
    tips: ["Best time is Sangai Festival (Nov)"],
    budget: "₹10,000 – ₹24,000", duration: "4 – 6 days",
    cities: ["Imphal", "Bishnupur", "Ukhrul"],
    tags: ["culture", "wildlife", "photography"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["manipur"], gallery: [img("mn-1"), img("mn-2"), img("mn-3"), img("mn-4")],
    emoji: "💎", tagline: "Jewel of India",
  },
  {
    id: "mizoram", name: "Mizoram", capital: "Aizawl", region: "Northeast",
    languages: ["Mizo"], bestTime: "October – March",
    attractions: ["Reiek Peak", "Vantawng Falls", "Champhai", "Phawngpui"],
    cuisine: ["Bai", "Bamboo Shoot Fry", "Sawhchiar"],
    festivals: ["Chapchar Kut", "Mim Kut", "Pawl Kut"],
    unesco: [], wildlife: ["Dampa Tiger Reserve"], hillStations: ["Aizawl", "Champhai"], beaches: [],
    culture: "Highlander heritage — bamboo dance, church spires, misty hills.",
    dress: "Puanchei", adventure: ["Trekking Phawngpui", "Paragliding Hmuifang"],
    funFacts: ["Second highest literacy rate", "One of the 3 states with a Christian majority"],
    tips: ["Need Inner Line Permit"],
    budget: "₹10,000 – ₹22,000", duration: "4 – 6 days",
    cities: ["Aizawl", "Lunglei", "Champhai"],
    tags: ["mountain", "culture", "adventure"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["mizoram"], gallery: [img("mz-1"), img("mz-2"), img("mz-3"), img("mz-4")],
    emoji: "⛰️", tagline: "Song of the Hills",
  },
  {
    id: "nagaland", name: "Nagaland", capital: "Kohima", region: "Northeast",
    languages: ["English", "Nagamese"], bestTime: "October – May",
    attractions: ["Hornbill Festival", "Dzukou Valley", "Kohima War Cemetery", "Khonoma Village"],
    cuisine: ["Smoked Pork with Bamboo Shoot", "Axone", "Galho"],
    festivals: ["Hornbill Festival", "Sekrenyi"],
    unesco: [], wildlife: ["Intanki NP"], hillStations: ["Dzukou", "Kohima"], beaches: [],
    culture: "16 tribes, warrior heritage, tribal weaves, Hornbill Festival draws the world.",
    dress: "Tribal shawls",
    adventure: ["Trek Dzukou", "Homestay village walks"],
    funFacts: ["Khonoma is India's first green village", "Hornbill Festival is 'Festival of Festivals'"],
    tips: ["Visit during Hornbill (Dec 1-10)", "Need Inner Line Permit"],
    budget: "₹12,000 – ₹28,000", duration: "5 – 7 days",
    cities: ["Kohima", "Dimapur", "Mokokchung"],
    tags: ["culture", "mountain", "adventure", "photography"] as any,
    seasons: ["winter"], budgetTier: 3,
    hero: HEROES["nagaland"], gallery: [img("nl-1"), img("nl-2"), img("nl-3"), img("nl-4")],
    emoji: "🪶", tagline: "Land of Festivals",
  },
  {
    id: "tripura", name: "Tripura", capital: "Agartala", region: "Northeast",
    languages: ["Bengali", "Kokborok"], bestTime: "October – March",
    attractions: ["Ujjayanta Palace", "Neermahal", "Unakoti Rock Carvings"],
    cuisine: ["Mui Borok", "Chakhwi", "Wahan Mosdeng"],
    festivals: ["Kharchi Puja", "Garia Puja"],
    unesco: [], wildlife: ["Sepahijala"], hillStations: ["Jampui Hills"], beaches: [],
    culture: "Small state — grand palaces, tribal art, Bengali fusion.",
    dress: "Rignai, Rikutu",
    adventure: ["Trekking Jampui", "Boating Neermahal"],
    funFacts: ["Neermahal is one of only 2 water palaces in India", "Unakoti has 30ft rock reliefs"],
    tips: ["Combine with Assam for NE trip"],
    budget: "₹8,000 – ₹18,000", duration: "3 – 5 days",
    cities: ["Agartala", "Udaipur (Tripura)", "Dharmanagar"],
    tags: ["culture", "history"] as any,
    seasons: ["winter"], budgetTier: 2,
    hero: HEROES["tripura"], gallery: [img("tr-1"), img("tr-2"), img("tr-3"), img("tr-4")],
    emoji: "🏰", tagline: "Land of Kings & Rivers",
  },
  {
    id: "sikkim", name: "Sikkim", capital: "Gangtok", region: "Northeast",
    languages: ["Nepali", "Bhutia", "Lepcha"], bestTime: "March – May, October – December",
    attractions: ["Tsomgo Lake", "Nathula Pass", "Yumthang Valley", "Rumtek Monastery", "Pelling"],
    cuisine: ["Momos", "Thukpa", "Gundruk", "Sel Roti"],
    festivals: ["Losar", "Saga Dawa", "Pang Lhabsol"],
    unesco: ["Khangchendzonga NP"],
    wildlife: ["Khangchendzonga NP"], hillStations: ["Gangtok", "Pelling", "Lachung"], beaches: [],
    culture: "Himalayan gem — Kanchenjunga views, monasteries, organic farming.",
    dress: "Bakhu, Kho",
    adventure: ["Trekking Goecha La", "Yak safari", "River rafting Teesta"],
    funFacts: ["India's first 100% organic state", "Home to Kanchenjunga — world's 3rd highest peak"],
    tips: ["Need permit for Nathula/Tsomgo", "Book Yumthang early"],
    budget: "₹12,000 – ₹28,000", duration: "5 – 7 days",
    cities: ["Gangtok", "Pelling", "Lachung", "Namchi"],
    tags: ["mountain", "snow", "adventure", "honeymoon", "photography"] as any,
    seasons: ["winter", "summer"], budgetTier: 3,
    hero: HEROES["sikkim"], gallery: [img("sk-1"), img("sk-2"), img("sk-3"), img("sk-4")],
    emoji: "🏔️", tagline: "The Himalayan Jewel",
  },
];

export const REGIONS = ["North", "South", "East", "West", "Central", "Northeast"] as const;

export function getState(id: string) {
  return STATES.find((s) => s.id === id);
}
